services:
  backend:
    image: faculuna27/banking-backend:latest
    container_name: banking-backend
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: 3306
      DB_NAME: banking_system_db
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: always
    ports:
      - "8080:8080"

  frontend:
    image: faculuna27/banking-frontend:latest
    container_name: banking-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
